import assert from './test-assert';
import { applyPlanetCommand, emptyPlanet, paperHolds, reducePaper, initialPaper, parsePlanet } from '../src/features/planet/paper-post-engine';

assert.equal(paperHolds({ shape: 'flat', gap: 'wide', parcels: 1 }), false);
assert.equal(paperHolds({ shape: 'folded', gap: 'short', parcels: 1 }), true);
assert.equal(paperHolds({ shape: 'accordion', gap: 'wide', parcels: 3 }), false);
assert.equal(paperHolds({ shape: 'accordion', gap: 'short', parcels: 3 }), true);
const context = { profileId: 'fixture', ageBand: '8-9' as const, family: false, now: '2026-09-13T10:00:00Z' };
const start = (id: string) => ({ type: 'start' as const, id, scenarioId: 'first-parcel' as const });
let data = applyPlanetCommand(emptyPlanet(), start('one'), context);
assert.throws(() => applyPlanetCommand(data, start('two'), context), /Resume/);
assert.throws(() => applyPlanetCommand(emptyPlanet(), { ...start('paid'), scenarioId: 'wide-gap' }, context), /membership/);
assert.throws(() => applyPlanetCommand(data, { type: 'finish', sessionId: 'one' }, context), /Test/);
data = applyPlanetCommand(data, { type: 'act', sessionId: 'one', action: { type: 'shape', value: 'folded' } }, context);
data = applyPlanetCommand(data, { type: 'act', sessionId: 'one', action: { type: 'test' } }, context);
data = applyPlanetCommand(data, { type: 'finish', sessionId: 'one' }, context);
assert.equal(data.artifacts.length, 1);
assert.equal(data.session, null);
assert.deepEqual(applyPlanetCommand(data, { type: 'finish', sessionId: 'one' }, context), data);
assert.equal(data.outcomes[0].evidence.length, 1);
const young = { ...context, ageBand: '6-7' as const };
let youngData = applyPlanetCommand(emptyPlanet(), start('young'), young);
assert.throws(() => applyPlanetCommand(youngData, { type: 'act', sessionId: 'young', action: { type: 'test' } }, young), /grown-up/);
youngData = applyPlanetCommand(youngData, { type: 'act', sessionId: 'young', action: { type: 'introduce' } }, young);
assert.doesNotThrow(() => applyPlanetCommand(youngData, { type: 'act', sessionId: 'young', action: { type: 'test' } }, young));
let paid = applyPlanetCommand(emptyPlanet(), { ...start('paid'), scenarioId: 'wide-gap' }, { ...context, family: true });
paid = applyPlanetCommand(paid, { type: 'act', sessionId: 'paid', action: { type: 'shape', value: 'accordion' } }, context);
paid = applyPlanetCommand(paid, { type: 'act', sessionId: 'paid', action: { type: 'test' } }, context);
assert.equal(applyPlanetCommand(paid, { type: 'finish', sessionId: 'paid' }, context).artifacts.length, 1, 'expiry permits finishing');
for (let i = 1; i < 12; i++) {
  data = applyPlanetCommand(data, start(`item-${i}`), context);
  data = applyPlanetCommand(data, { type: 'act', sessionId: `item-${i}`, action: { type: 'shape', value: 'accordion' } }, context);
  data = applyPlanetCommand(data, { type: 'act', sessionId: `item-${i}`, action: { type: 'test' } }, context);
  data = applyPlanetCommand(data, { type: 'finish', sessionId: `item-${i}` }, context);
}
data = applyPlanetCommand(data, start('last'), context);
data = applyPlanetCommand(data, { type: 'act', sessionId: 'last', action: { type: 'shape', value: 'accordion' } }, context);
data = applyPlanetCommand(data, { type: 'act', sessionId: 'last', action: { type: 'test' } }, context);
assert.throws(() => applyPlanetCommand(data, { type: 'finish', sessionId: 'last' }, context), /Choose/);
const before = data.artifacts;
data = applyPlanetCommand(data, { type: 'finish', sessionId: 'last', replaceArtifactId: before[0].id }, context);
assert.equal(data.artifacts.length, 12);
data = applyPlanetCommand(data, { type: 'undo-replacement' }, context);
assert.deepEqual(data.artifacts, before);
assert.deepEqual(parsePlanet(JSON.stringify(data)), data);
assert.throws(() => parsePlanet('{oops'), /saved planet/);
const state = reducePaper(initialPaper('sandbox'), { type: 'test' });
assert.equal(reducePaper(state, { type: 'gap', value: 'short' }).result, null, 'changes require a fresh test');
console.log('Pocket Planet: qualitative model, age handoff, membership, duplicate completion, capacity, undo and parsing passed.');
